[202012] For LGTM, fix up Doxyfile to make it work for new versions of Doxygen
Azure/sonic-sairedis pull request #1012
Opened 2022-03-01 23:12 UTC by saiarcot895

LGTM is now using Ubuntu 20.04 for compilations. As part of this, newer versions of Doxygen use a different syntax for representing newlines in aliases defined in Doxyfile. Try to fix this from the LGTM config.

Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

2022-03-02 00:42 UTC, saiarcot895 commented
LGTM build with this commit is passing, but the base commit (the current 202012 branch) is failing, which makes sense since the fix isn't there.

2022-03-02 15:07 UTC, kcudnik requested changes
this is not correct fix, correct fix is to update SAI submodule with this change: https://github.com/opencomputeproject/SAI/pull/1424

2022-03-03 00:51 UTC, saiarcot895 commented
I was looking into that, but for some reason, I thought there were multiple commits that would come in if i did a submodule update to bring in that fix. I think I was looking at the v1.9 branch instead of the v1.7 branch.

I've raised a PR at opencomputeproject/SAI#1414 to backport the fix to v1.7.

2022-03-03 19:26 UTC, kcudnik approved these changes

2022-03-04 23:25 UTC, merged