[201911 sonic-sairedis] modified LOG_ERROR to LOG_WARN for port flush events
Azure/sonic-sairedis pull request #724
Opened 2020-12-01 19:19 UTC by madhanmellanox

Error logs were reported for sonic-sairedis when trying to remove a bridge port. Because of the complexity to port it to 201911 branch, modified LOG_ERROR to LOG_WARN for port flush events.

2020-12-01 19:49 UTC, kcudnik commented
those should be actually error, since code was not developed for this

2020-12-01 19:51 UTC, kcudnik approved these changes

2020-12-03 07:17 UTC, liat-grozovik approved these changes

2020-12-03 14:46 UTC, kcudnik commented
I will make PR to add proper handling for those, so this PR will not be needed

2020-12-03 15:15 UTC, kcudnik commented
https://github.com/Azure/sonic-sairedis/pull/726

2020-12-04 13:21 UTC, kcudnik requested changes
i think this PR can be droped since i posted fix

2020-12-04 20:37 UTC, madhanmellanox commented
Closing this PR, since this is a workaround PR and now we have a fix PR.

2020-12-04 20:37 UTC, closed without merging