Switch Capability support
Azure/sonic-sairedis pull request #728
Opened 2020-12-06 10:11 UTC by PrabhuSreenivasan

Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom.com>

Adds SAI_SWITCH_ATTR_SUPPORTED_OBJECT_TYPE_LIST to switch attributes.

Related PRs:
https://github.com/Azure/sonic-swss/pull/1525

2020-12-06 10:18 UTC, kcudnik commented on vslib/src/SwitchStateBase.cpp
> +                              };
actually all objects are supported, you can create any objects, but not all read only attributes will work, they need to be refreshed manually

2020-12-06 10:18 UTC, kcudnik commented on vslib/src/SwitchStateBase.cpp
> +    attr.value.s32list.count = sizeof(supported_obj_list);
sizeof(supported_obj_list)/sizeof(int32_t) ??

2020-12-06 10:19 UTC, kcudnik commented on vslib/src/SwitchStateBase.cpp
> +                              };
also NULL object should not be on that list ?

2020-12-06 10:19 UTC, kcudnik commented on vslib/src/SwitchStateBase.cpp
> +                              };
use std::vector<sai_object_type_t> maybe ?

2020-12-06 10:21 UTC, kcudnik commented on vslib/src/SwitchStateBase.cpp
> +                              };
also move that closes to the first use

2020-12-06 10:21 UTC, kcudnik requested changes
address comments

2020-12-07 10:30 UTC, kcudnik commented
can you also add here unittests for this ? you can add them in vslib/src/tests.cpp

2020-12-07 10:32 UTC, kcudnik commented on vslib/src/SwitchStateBase.cpp
> +    int32_t supported_obj_list[] = {
change to sai_object_type_t instead of int32_t

2020-12-07 13:43 UTC, PrabhuSreenivasan commented
> can you also add here unittests for this ? you can add them in vslib/src/tests.cpp

sure. I will add the same.

2020-12-07 18:17 UTC, kcudnik requested changes

2020-12-07 18:17 UTC, kcudnik commented on vslib/src/tests.cpp
> +    std::vector<sai_object_id_t> supported_obj_list;
please make this separate method, you added your case in test_get_stats, and your changes are not related to stats

2020-12-08 09:41 UTC, kcudnik approved these changes

2020-12-08 11:07 UTC, kcudnik commented
retest vs please

2020-12-13 07:37 UTC, merged