Rename duplicate file name
Azure/sonic-sairedis pull request #773
Opened 2021-01-22 04:19 UTC by chaoskao

What I did:
Rename duplicate file name.

Why I did it:
It it hard to checkout code to non-case sensitive system.

How I verified it:
Use git clone repo to Windows or OSX and code build success by mount to the docker.

2021-01-22 18:02 UTC, kcudnik commented
retest vs please

2021-01-22 18:05 UTC, kcudnik commented
saiattributelist.h i used in swss orchagent, without this it will probably fail

2021-01-22 18:07 UTC, kcudnik reviewed
please rename files in some fashion not to use "_" as starting file name

2021-01-22 18:07 UTC, kcudnik commented on syncd/Makefile.am
> +				_syncd.cpp \
rename to syncd_main.cpp

2021-01-22 18:07 UTC, kcudnik commented on saiplayer/Makefile.am
> +saiplayer_SOURCES = _saiplayer.cpp
rename to saiplayer_main.cpp

2021-01-22 18:08 UTC, kcudnik requested changes
please rename files in some fashion not to use "_" as starting file name

2021-01-22 18:08 UTC, kcudnik commented
are you planning to build entire sonic image on windows/osx?

2021-01-25 10:18 UTC, chaoskao commented on syncd/Makefile.am
> +				_syncd.cpp \
ok

2021-01-25 10:29 UTC, chaoskao commented
I check the saiattributelist.h only used in mock_tests/check.h, others used the SaiAttributeList.h. Maybe we can rename to saiattributelist_mock.h?
I am not planning to build sonic-buildimage on Windows/OSX, just git clone to Windows/OSX and mount to docker do some test.

2021-01-25 13:34 UTC, kcudnik commented
> I check the saiattributelist.h only used in mock_tests/check.h, others used the SaiAttributeList.h. Maybe we can rename to saiattributelist_mock.h?

this is used in sonic-swss repo, and i think it needs to be fixed there

2021-01-29 03:06 UTC, chaoskao commented
Hi @kcudnik you can reference this [branch ](https://github.com/chaoskao/sonic-swss/tree/legacy_code) for your PR [Azure/sonic-swss#1608](https://github.com/Azure/sonic-swss/pull/1608)

2021-01-29 14:21 UTC, kcudnik commented
what do you mean?

2021-02-08 17:50 UTC, kcudnik commented
swss-common was merged, and you can remove that saiattributelist.h file completely

2021-02-10 13:24 UTC, kcudnik approved these changes

2021-02-10 13:25 UTC, merged