Update FlexCounter.cpp, use m_pollInterval in MUTEX lock
Azure/sonic-sairedis pull request #798
Opened 2021-02-16 02:02 UTC by ryan44guo

m_pollInterval is used out of the MUTEX lock，when set to a smaller value, it may result of wait for a very long time.

2021-02-17 09:09 UTC, kcudnik requested changes
can you explain case in the description? also value supplied to wait_for is the same, so what the actual change is made here?

2021-02-18 01:14 UTC, ryan44guo commented
I have encountered one case. the m_pollInterval is 1000 at first, and the delay is 98870, so in the old code, the correction is 870. you know, the lock is unlocked, and the action setting m_pollInterval to 100 which waiting for this lock is executed. so when the wait_for function executed, the value used is 100-870=0xfffffcfe, and this thread is blocking here.

2021-02-18 06:20 UTC, kcudnik commented
im not sure if i get it, the value still will be 0xfffffcfe before mutex or after mutex anyway

2021-02-18 07:46 UTC, ryan44guo commented
after my modification, the use of m_pollInterval is used in the lock, it can not be modified before unlock. cause the set action is in the lock too.

2021-02-18 09:39 UTC, kcudnik reviewed
got it

2021-02-18 09:39 UTC, kcudnik approved these changes

2021-02-18 09:40 UTC, merged